sudo: false
dist: trusty
language: csharp
mono:
  # Debian 9 Stretch provides v4.6.2.7
  - 4.6.2
  # Visual Studio for Mac 7.2 provides v5.4.0
  # but latest provided currently is 5.2 per
  # http://download.mono-project.com/repo/debian/dists/wheezy/snapshots/
  - 5.2.0
script:
  - cd src/CVNBot
  - xbuild CVNBot.csproj /p:Configuration=Release
  - xbuild CVNBot.csproj /p:Configuration=Debug
