dist: bionic
language: csharp
# Travis CI uses this repository:
# http://download.mono-project.com/repo/ubuntu/dists/stable-bionic/snapshots/
mono:
  # In production at cvn.wmflabs.org, we run Debian 9 Stretch with 5.16 from
  # https://download.mono-project.com/repo/debian/dists/stable-stretch/snapshots/
  # See also https://github.com/countervandalism/infrastructure/blob/2906b10516/setup.yaml#L132
  - '5.16.0'
  # Visual Studio Community 2019 (Visual Studio 8.5) for Mac provides Mono 6.8.0 (used by Krinkle)
  - '6.8.0'
script:
  - msbuild src/CVNBot.sln /p:Configuration=Release
  - msbuild src/CVNBot.sln /p:Configuration=Debug
notifications:
  irc:
    channels:
      - "chat.freenode.net#countervandalism"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit}: %{author}) %{message} - %{build_url}"
